parameters:
#    pro4_user.example.class: PRO4\UserBundle\Example

services:
#    pro4_user.example:
#        class: %pro4_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
