homepage:
    pattern: /
    defaults: { _controller: PRO4LoginBundle:Login:index }

login:
    pattern:  /login/
    defaults: { _controller: PRO4LoginBundle:Login:login }

login_check:
    pattern: /loginCheck/

register:
    pattern:  /register/
    defaults: { _controller: PRO4LoginBundle:Login:register }

logout:
    pattern: /logout
    defaults: { _controller: PRO4LoginBundle:Login:logout }



change_password:
    pattern: /app/change-password
    defaults: { _controller: PRO4UserBundle:User:changePassword }



project:
    pattern: /app/project/
    defaults: { _controller: PRO4ProjectBundle:Project:index }
    
add_project:
    pattern: /app/project/add
    defaults: { _controller: PRO4ProjectBundle:Project:addProject }

project_detail:
    pattern: /app/project/{id}/
    defaults: { _controller: PRO4ProjectBundle:Project:projectDetail }
    
edit_project_detail:
    pattern: /app/project/{id}/edit
    defaults: { _controller: PRO4ProjectBundle:Project:editProjectDetail }
    
    
    
users_in_project:
    pattern: /app/project/{id}/users/
    defaults: { _controller: PRO4ProjectBundle:UsersInProject:index }

remove_user_from_project:
    pattern: /app/project/{projectId}/users/{userId}/remove
    defaults: { _controller: PRO4ProjectBundle:UsersInProject:remove }
    
grant_admin_in_project:
    pattern: /app/project/{projectId}/users/{userId}/grantAdmin
    defaults: { _controller: PRO4ProjectBundle:UsersInProject:grantAdmin }
    
revoke_admin_in_project:
    pattern: /app/project/{projectId}/users/{userId}/revokeAdmin
    defaults: { _controller: PRO4ProjectBundle:UsersInProject:revokeAdmin }



department_overview:
    pattern: /app/project/{projectId}/departments/
    defaults: { _controller: PRO4ProjectBundle:Department:index }
    
remove_department:
    pattern: /app/project/{projectId}/departments/{departmentId}/remove
    defaults: { _controller: PRO4ProjectBundle:Department:remove }
    
edit_department:
    pattern: /app/project/{projectId}/departments/{departmentId}/edit
    defaults: { _controller: PRO4ProjectBundle:Department:edit }
    
    
    
users_in_department:
    pattern: /app/project/{projectId}/departments/{departmentId}
    defaults: { _controller: PRO4ProjectBundle:Department:usersInDepartment }
    
remove_user_from_department:
    pattern: /app/project/{projectId}/departments/{departmentId}/user/{userId}/remove
    defaults: { _controller: PRO4ProjectBundle:Department:removeUserFromDepartment }
    
grant_admin_in_department:
    pattern: /app/project/{projectId}/departments/{departmentId}/user/{userId}/grantAdmin
    defaults: { _controller: PRO4ProjectBundle:Department:grantAdminInDepartment }
    
revoke_admin_in_department:
    pattern: /app/project/{projectId}/departments/{departmentId}/user/{userId}/revokeAdmin
    defaults: { _controller: PRO4ProjectBundle:Department:revokeAdminInDepartment }



to_do_lists:
    pattern: /app/project/{projectId}/to-do/
    defaults: { _controller: PRO4ToDoListBundle:ToDoList:index }
    
edit_to_do_list:
    pattern: /app/project/{projectId}/to-do/{toDoListId}/edit
    defaults: { _controller: PRO4ToDoListBundle:ToDoList:editToDoList }
    
add_to_do_list_item:
    pattern: /app/project/{projectId}/to-do/{toDoListId}/addItem
    defaults: { _controller: PRO4ToDoListBundle:ListItem:addItem }

complete_to_do_list_item:
    pattern: /app/project/{projectId}/to-do/{toDoListId}/items/{itemId}/complete
    defaults: { _controller: PRO4ToDoListBundle:ListItem:completeItem } 
    
undo_to_do_list_item:
    pattern: /app/project/{projectId}/to-do/{toDoListId}/items/{itemId}/undo
    defaults: { _controller: PRO4ToDoListBundle:ListItem:undoItem } 
    
delete_to_do_list_item:
    pattern: /app/project/{projectId}/to-do/{toDoListId}/items/{itemId}/delete
    defaults: { _controller: PRO4ToDoListBundle:ListItem:deleteItem }    
    


calendar:
    pattern: /app/project/{projectId}/calendar/
    defaults: { _controller: PRO4CalendarBundle:Calendar:index }

show_calendar:
    pattern: /app/project/{projectId}/calendar/{year}/{monthNo}
    defaults: { _controller: PRO4CalendarBundle:Calendar:addEvent }

edit_event:
    pattern: /app/project/{projectId}/calendar/{year}/{monthNo}/event/{eventId}/edit
    defaults: { _controller: PRO4CalendarBundle:Calendar:editEvent }
    


milestone_plan:
    pattern: /app/project/{id}/milestone_plan/
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:index }
    
milestone_overview:
    pattern: /app/project/{id}/milestone_plan/overview
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:overview }

edit_milestone_plan:
    pattern: /app/project/{id}/milestone_plan/edit
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:editMilestonePlan }
    
add_milestone:
    pattern: /app/project/{projectId}/milestone_plan/{milestonePlanId}/milestone/add
    defaults: { _controller: PRO4MilestoneBundle:Milestone:add }

edit_milestone:
    pattern: /app/project/{projectId}/milestone_plan/{milestonePlanId}/milestone/{milestoneId}/edit
    defaults: { _controller: PRO4MilestoneBundle:Milestone:edit }



files:
    pattern: /app/project/{projectId}/files/
    defaults: { _controller: PRO4FileBundle:File:index }
    
    

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
