homepage:
    pattern: /
    defaults: { _controller: PRO4LoginBundle:Login:index }

login:
    pattern:  /login/
    defaults: { _controller: PRO4LoginBundle:Login:login }

login_check:
    pattern: /loginCheck/

register:
    pattern:  /register/
    defaults: { _controller: PRO4LoginBundle:Login:register }

logout:
    pattern: /logout
    defaults: { _controller: PRO4LoginBundle:Login:logout }


project:
    pattern: /app/project/
    defaults: { _controller: PRO4ProjectBundle:Project:index }
    
add_project:
    pattern: /app/project/add/
    defaults: { _controller: PRO4ProjectBundle:Project:addProject }

project_detail:
    pattern: /app/project/{id}
    defaults: { _controller: PRO4ProjectBundle:Project:projectDetail }
    
edit_project_detail:
    pattern: /app/project/{id}/edit
    defaults: { _controller: PRO4ProjectBundle:Project:editProjectDetail }
    
users_in_project:
    pattern: /app/project/{id}/users
    defaults: { _controller: PRO4ProjectBundle:UsersInProject:index }


milestone_plan:
    pattern: /app/project/{id}/milestone_plan/
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:index }
    
milestone_overview:
    pattern: /app/project/{id}/milestone_plan/overview
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:overview }

edit_milestone_plan:
    pattern: /app/project/{id}/milestone_plan/edit
    defaults: { _controller: PRO4MilestoneBundle:MilestonePlan:editMilestonePlan }
    
add_milestone:
    pattern: /app/project/{projectId}/milestone_plan/{milestonePlanId}/milestone/add
    defaults: { _controller: PRO4MilestoneBundle:Milestone:addMilestone }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
