pro4_login_login:
    pattern:  /
    defaults: { _controller: PRO4LoginBundle:Login:index }

pro4_login_register:
    pattern:  /register/
    defaults: { _controller: PRO4LoginBundle:Login:register }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
