homepage:
    pattern: /
    defaults: { _controller: PRO4LoginBundle:Login:index}

login:
    pattern:  /login
    defaults: { _controller: PRO4LoginBundle:Login:login}

login_check:
    pattern: /loginCheck

register:
    pattern:  /register
    defaults: { _controller: PRO4LoginBundle:Login:register }

logout:
    pattern: /logout
    defaults: { _controller: PRO4LoginBundle:Login:logout }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
