jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PRO4\UserBundle\Entity\User: sha1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: PRO4UserBundle:User, property: eMail }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        app:
            pattern: ^/
            form_login: 
                check_path: login_check
                login_path: login
                
                always_use_default_target_path: false
                default_target_path: /app/project
                
                username_parameter: email
                password_parameter: password
            logout:
              path: /logout
              target: /
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/app, roles: ROLE_USER }
