parameters:
#    pro4_login.example.class: PRO4\LoginBundle\Example

services:
#    pro4_login.example:
#        class: %pro4_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]