parameters:
#    pro4_main.example.class: PRO4\MainBundle\Example

services:
#    pro4_main.example:
#        class: %pro4_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
