parameters:
#    pro4_milestone.example.class: PRO4\MilestoneBundle\Example

services:
#    pro4_milestone.example:
#        class: %pro4_milestone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
