parameters:
#    pro4_event.example.class: PRO4\EventBundle\Example

services:
#    pro4_event.example:
#        class: %pro4_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
