parameters:
#    pro4_to_do_list.example.class: PRO4\ToDoListBundle\Example

services:
#    pro4_to_do_list.example:
#        class: %pro4_to_do_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
